const ROLES = require("./roles");

const PERMISSIONS = {
  USER_MANAGEMENT: [ROLES.ADMIN],

  CAMPAIGNS: [ROLES.ADMIN, ROLES.CAMPAIGN_MANAGER],

  DASHBOARD_ANALYTICS: [ROLES.ADMIN, ROLES.CAMPAIGN_MANAGER, ROLES.TEAM_LEAD],

  CAMPAIGN_ANALYTICS: [ROLES.ADMIN, ROLES.CAMPAIGN_MANAGER, ROLES.TEAM_LEAD],

  INBOX: [ROLES.ADMIN, ROLES.SUPPORT_AGENT, ROLES.TEAM_LEAD],

  TEMPLATE_VIEW: [
    ROLES.ADMIN,
    ROLES.CAMPAIGN_MANAGER,
    ROLES.SUPPORT_AGENT,
    ROLES.TEAM_LEAD,
  ],

  TEMPLATE_MANAGE: [ROLES.ADMIN, ROLES.CAMPAIGN_MANAGER],

  TEMPLATE_DELETE: [ROLES.ADMIN],

  SETTINGS: [ROLES.ADMIN],

  ASSIGN_CONVERSATION: [ROLES.ADMIN, ROLES.TEAM_LEAD],

  CONTACTS: [
    ROLES.ADMIN,
    ROLES.CAMPAIGN_MANAGER,
    ROLES.SUPPORT_AGENT,
    ROLES.TEAM_LEAD,
  ],
};

module.exports = PERMISSIONS;
